version: "3.6"

services:
  app: &app
    restart: always
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: gunicorn --workers=3 grind.wsgi:application --reload --bind 0.0.0.0:8000
    volumes:
      - ../../src/:/home/projects/grind # hot reload
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    depends_on:
      - db
      - rabbitmq
      - celery
    environment:
      DJANGO_SETTINGS_MODULE: grind.settings.dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: grind
      DB_HOST: db
      DB_PORT: 5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/v1/accounts/"]
      interval: 5s
      timeout: 10s
      retries: 3
    stdin_open: true #interactive debugging
    tty: true
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grind
    ports:
      - "5432:5432"
    env_file:
      - ../../.env
    container_name: grind_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 0.0.0.0 -p 5432 -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.7-alpine
    env_file:
      - ../../.env
    ports:
      - 5672:5672
  celery:
    # Run our `app` with the celery service
    <<: *app
    command: celery -A grind worker --loglevel=info
    # disable ports to prevent conflict
    env_file:
      - ../../.env
    environment:
      DJANGO_SETTINGS_MODULE: grind.settings.dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: grind
      DB_HOST: db
      DB_PORT: 5432
    ports: []
    depends_on:
      - rabbitmq
      - db
volumes:
  postgres_data:
