version: '3.6'

services:
  app:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source # ensure changes made in the sourcecode are reflected in the container without rebuilding it
    ports:
      - "8080:8000"
    depends_on:
      - db
    container_name: grind_app
    environment:
      DJANGO_SETTINGS_MODULE: grind.settings.base
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=grind
      - POSTGRES_PASSWORD=grind
      - POSTGRES_DB=grind
    ports: 
     - "5432:5432"
    container_name: grind_db
