# Generated by Django 2.2.4 on 2019-11-19 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191105_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be 5 or more alphabetic characters', regex='^[a-zA-Z]{5,}$')]),
        ),
    ]
